services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network
    env_file:
      - .env  

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: >
      bash -c "
        npm install &&
        npm run start:dev
      "
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
